<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\TextDocument.cs" Link="TextDocument.cs" />
    <Compile Include="..\HotKeyBinding.cs" Link="HotKeyBinding.cs" />
    <Compile Include="..\NativeMethods.cs" Link="NativeMethods.cs" />
    <Compile Include="..\GlobalUsings.cs" Link="GlobalUsings.cs" />
  </ItemGroup>
</Project>
